server:
  port: 8088

spring:
  application:
    name: bill-service
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI:http://localhost:8082/realms/digital-media}
        registration:
          microservicios:
            provider: keycloak
            client-id: microservicios
            client-secret: "**********"
            scope: openid
            redirect-uri: ${REDIRECT_URI:http://localhost:8088}

app:
    cors:
        allowed-origins: http://localhost:3000
    realm: digital-media
    realm-cert: ${CERT_URI:http://localhost:8080/realms/digital-media/protocol/openid-connect/certs}
    url-user-service: ${URL_USER_SERVICE:http://localhost:8087}

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}